const smartTVs = [
  {
    id: 1,
    name_en: 'Samsung QN90D Neo QLED 4K Smart TV 55"',
    name_fr: 'Samsung QN90D Neo QLED TV intelligente 4K 55"',
    brand: "Samsung",
    category: "Neo QLED",                             
    price: 649900,
    oldPrice: 699900,
    size_en: "55 inches",
    size_fr: "55 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748732778/Samsung_QN90D_Neo_QLED_4K_Smart_TV_55_tgojyk.png",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748732778/Samsung_QN90D_Neo_QLED_4K_Smart_TV_55_tgojyk.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748733332/Samsung_QN90D_Neo_QLED_4K_Smart_TV_55_3_bceyxu.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748733332/Samsung_QN90D_Neo_QLED_4K_Smart_TV_55_3_bceyxu.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748733455/Samsung_QN90D_Neo_QLED_4K_Smart_TV_55_4_ovjn9s.png",
    ],
    tags: ["Samsung", "Neo QLED", "4K", "Smart TV", "55 inch"],
    description_en:
      "Experience cinematic brilliance at home with the Samsung QN90D Neo QLED 4K Smart TV (55\"). Powered by Samsung's Quantum Matrix Technology, this premium display delivers breathtaking contrast, ultra-deep blacks, and vivid colors in stunning 4K resolution.",
    description_fr:
      "Vivez l'éclat cinématographique à la maison avec le téléviseur intelligent Samsung QN90D Neo QLED 4K (55\"). Alimenté par la technologie Quantum Matrix de Samsung, cet écran haut de gamme offre un contraste époustouflant, des noirs ultra-profonds et des couleurs vives en résolution 4K.",
    detailedDescription_en:
      'The Samsung QN90D Neo QLED 55" Smart TV delivers exceptional picture quality with Quantum Matrix Technology and 4K UHD resolution. Its ultra-precise light control produces true blacks, bright highlights, and unparalleled contrast, all powered by the advanced Neural Quantum Processor 4K. With built-in smart features, this TV offers seamless access to your favorite streaming apps, voice control, and multi-device connectivity.',
    detailedDescription_fr:
      "Le téléviseur intelligent Samsung QN90D Neo QLED 55\" offre une qualité d'image exceptionnelle grâce à la technologie Quantum Matrix et à la résolution 4K UHD. Son contrôle précis de la lumière permet d'obtenir des noirs profonds, des hautes lumières éclatantes et un contraste inégalé, le tout alimenté par le processeur Neural Quantum 4K. Avec ses fonctions intelligentes intégrées, ce téléviseur vous donne un accès fluide à vos applications de streaming préférées.",
    features_en: [
      "Quantum Dot Technology",
      "AI-Powered Upscaling",
      "HDR10+ Support",
      "Multiple HDMI Ports",
      "Voice Control",
    ],
    features_fr: [
      "Technologie Quantum Dot",
      "Mise à l'échelle alimentée par IA",
      "Support HDR10+",
      "Ports HDMI multiples",
      "Contrôle vocal",
    ],
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 120,
    language: ["English", "French"],
  },
  {
    id: 2,
    name_en: 'LG OLED evo C3 65" 4K Smart TV',
    name_fr: 'LG OLED evo C3 TV intelligente 4K 65"',
    brand: "LG",
    category: "OLED",
    price: 799900,
    oldPrice: 849900,
    size_en: "65 inches",
    size_fr: "65 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748735531/LG_OLED_evo_C3_65_4K_Smart_TV_ra0omw.png",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748735531/LG_OLED_evo_C3_65_4K_Smart_TV_ra0omw.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748735553/LG_OLED_evo_C3_65_4K_Smart_TV_2_aekukm.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748735592/LG_OLED_evo_C3_65_4K_Smart_TV_3_jxovnk.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748735623/LG_OLED_evo_C3_65_4K_Smart_TV_4_ugmwua.png",
    ],
    tags: ["LG", "OLED", "4K", "Smart TV", "65 inch"],
    description_en: "Enjoy perfect black levels and infinite contrast with self-lighting OLED pixels.",
    description_fr: "Profitez de noirs parfaits et d'un contraste infini avec les pixels OLED auto-éclairés.",
    detailedDescription_en:
      "The LG OLED evo C3 is a 65-inch premium Smart TV that redefines realism. With self-lighting OLED pixels, it delivers perfect black levels, vibrant color accuracy, and infinite contrast for cinematic clarity. Its α9 AI Processor Gen6 ensures every frame is sharp, fluid, and beautifully detailed.",
    detailedDescription_fr:
      "Le LG OLED evo C3 est un téléviseur intelligent de 65 pouces qui redéfinit le réalisme. Grâce à ses pixels OLED auto-émissifs, il offre des noirs parfaits, une précision des couleurs exceptionnelle et un contraste infini pour une clarté cinématographique. Son processeur α9 AI Gen6 garantit une image nette, fluide et riche en détails.",
    features_en: ["Self-Lighting OLED", "Dolby Vision IQ", "NVIDIA G-Sync Support", "AI Picture Pro", "webOS Platform"],
    features_fr: [
      "OLED auto-éclairé",
      "Dolby Vision IQ",
      "Support NVIDIA G-Sync",
      "AI Picture Pro",
      "Plateforme webOS",
    ],
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 150,
    language: ["English", "French"],
  },
  {
    id: 3,
    name_en: 'Sony Bravia 3 50" 4K HDR Google TV',
    name_fr: 'Sony Bravia 3 50" 4K HDR Google TV',
    brand: "Sony",
    category: "LED",
    price: 499900,
    oldPrice: 549900,
    size_en: "50 inches",
    size_fr: "50 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748740995/Sony_Bravia_3_50_4K_HDR_Google_TV_45_zzagyp.png",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748740995/Sony_Bravia_3_50_4K_HDR_Google_TV_45_zzagyp.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748737130/Sony_Bravia_3_50_4K_HDR_Google_TV_2_akomcv.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748737200/Sony_Bravia_3_50_4K_HDR_Google_TV_3_f03nhk.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748738733/Sony_Bravia_3_50_4K_HDR_Google_TV_44-Photoroom_ty6jdr.png",
    ],
    tags: ["Sony", "Bravia", "4K", "Smart TV", "50 inch"],
    description_en: "Experience vibrant visuals and immersive sound with Google TV integration.",
    description_fr: "Découvrez des visuels éclatants et un son immersif grâce à l'intégration de Google TV.",
    detailedDescription_en:
      'The Sony Bravia 3 50" 4K HDR TV blends advanced picture technology with smart convenience. Its X1 4K HDR processor enhances every scene, delivering brilliant contrast, lifelike colors, and ultra-clear detail.',
    detailedDescription_fr:
      "Le Sony Bravia 3 50\" 4K HDR allie technologie d'image avancée et commodité intelligente. Son processeur X1 4K HDR améliore chaque scène, offrant un contraste saisissant, des couleurs naturelles et une netteté remarquable.",
    features_en: [
      "4K HDR Processor",
      "Google TV Interface",
      "Dolby Vision Support",
      "Motionflow XR",
      "Built-in Chromecast",
    ],
    features_fr: [
      "Processeur 4K HDR",
      "Interface Google TV",
      "Prise en charge de Dolby Vision",
      "Motionflow XR",
      "Chromecast intégré",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.5,
    reviews: 80,
    language: ["English", "French"],
  },
  {
    id: 4,
    name_en: 'TCL 43" Q Class 4K UHD HDR QLED Smart TV',
    name_fr: 'TCL 43" Q Class 4K UHD HDR QLED intelligente TV',
    brand: "TCL",
    category: "QLED",
    price: 349900,
    oldPrice: 399900,
    size_en: "43 inches",
    size_fr: "43 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748920450/TCL_43_Q_Class_4K_UHD_HDR_QLED_Smart_TV__brr6ys.png",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748920450/TCL_43_Q_Class_4K_UHD_HDR_QLED_Smart_TV__brr6ys.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748920475/TCL_43_Q_Class_4K_UHD_HDR_QLED_Smart_TV_2_m292vk.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748920519/TCL_43_Q_Class_4K_UHD_HDR_QLED_Smart_TV_4_z6jkin.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748920546/TCL_43_Q_Class_4K_UHD_HDR_QLED_Smart_TV_3_zykxhs.png",
    ],
    tags: ["TCL", "QLED", "4K", "Smart TV", "43 inch"],
    description_en: "Enjoy vibrant colors and deep contrasts with Quantum Dot technology.",
    description_fr: "Profitez de couleurs éclatantes et de contrastes profonds grâce à la technologie Quantum Dot.",
    detailedDescription_en:
      "The TCL Q Class delivers exceptional picture quality with Quantum Dot technology and 4K UHD resolution.",
    detailedDescription_fr:
      "Le TCL Q Class offre une qualité d'image exceptionnelle avec la technologie Quantum Dot et la résolution 4K UHD.",
    features_en: [
      "Quantum Dot Technology",
      "Dolby Vision HDR",
      "Google TV Interface",
      "Auto Game Mode",
      "Built-in Chromecast",
    ],
    features_fr: [
      "Technologie Quantum Dot",
      "Dolby Vision HDR",
      "Interface Google TV",
      "Mode Jeu Auto",
      "Chromecast intégré",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.3,
    reviews: 60,
    language: ["English", "French"],
  },
  {
    id: 5,
    name_en: 'Hisense 58" Quantum ULED 4K Fire TV',
    name_fr: 'Hisense 58" Quantum ULED 4K Fire TV',
    brand: "Hisense",
    category: "ULED",
    price: 599900,
    oldPrice: 649900,
    size_en: "58 inches",
    size_fr: "58 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748921742/Hisense_58_Quantum_ULED_4K_Fire_TV_2_fcasez.jpg",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748921742/Hisense_58_Quantum_ULED_4K_Fire_TV_2_fcasez.jpg",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748922571/Hisense_58_Quantum_ULED_4K_Fire_TV_10_lap4gy.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748921763/Hisense_58_Quantum_ULED_4K_Fire_TV_ojw1tc.jpg",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748921781/Hisense_58_Quantum_ULED_4K_Fire_TV_4_x4q3lr.png",
    ],
    tags: ["Hisense", "ULED", "4K", "Smart TV", "58 inch"],
    description_en: "Experience cinematic quality with Quantum Dot and Dolby Vision support.",
    description_fr: "Découvrez une qualité cinématographique avec la prise en charge de Quantum Dot et Dolby Vision.",
    detailedDescription_en:
      "The Hisense Quantum ULED delivers stunning brightness and contrast with advanced display technology.",
    detailedDescription_fr:
      "Le Hisense Quantum ULED offre une luminosité et un contraste époustouflants avec une technologie d'affichage avancée.",
    features_en: ["Quantum Dot Technology", "Dolby Vision HDR", "Fire TV OS", "Motion Rate 240", "Alexa Built-in"],
    features_fr: ["Technologie Quantum Dot", "Dolby Vision HDR", "Fire TV OS", "Motion Rate 240", "Alexa intégré"],
    inStock: true,
    isFeatured: false,
    rating: 4.4,
    reviews: 70,
    language: ["English", "French"],
  },
  {
    id: 6,
    name_en: 'Samsung 65" QN85D Neo QLED 4K Smart TV',
    name_fr: 'Samsung 65" QN85D Neo QLED 4K intelligente TV',
    brand: "Samsung",
    category: "Neo QLED",
    price: 799900,
    oldPrice: 899900,
    size_en: "65 inches",
    size_fr: "65 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748924042/Samsung_65_QN85D_Neo_QLED_4K_Smart_TV_mm7clx.png",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748924042/Samsung_65_QN85D_Neo_QLED_4K_Smart_TV_mm7clx.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748923426/Samsung_65_QN85D_Neo_QLED_4K_Smart_TV_2_ltaftx.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748923457/Samsung_65_QN85D_Neo_QLED_4K_Smart_TV_3_qs1en6.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1748923489/Samsung_65_QN85D_Neo_QLED_4K_Smart_TV_4_z8wbjp.png",
    ],
    tags: ["Samsung", "Neo QLED", "4K", "Smart TV", "65 inch"],
    description_en:
      "Experience stunning visuals with Quantum Matrix Technology and Neo Quantum HDR+ for immersive viewing.",
    description_fr:
      "Découvrez des visuels époustouflants avec la technologie Quantum Matrix et Neo Quantum HDR+ pour une expérience immersive.",
    detailedDescription_en:
      "The Samsung QN85D combines advanced Neo QLED technology with smart features for an exceptional viewing experience.",
    detailedDescription_fr:
      "Le Samsung QN85D combine la technologie Neo QLED avancée avec des fonctionnalités intelligentes pour une expérience de visionnage exceptionnelle.",
    features_en: [
      "Quantum Matrix Technology",
      "Neo Quantum HDR+",
      "Dolby Atmos®",
      "Motion Xcelerator 120Hz",
      "Built-in Alexa",
    ],
    features_fr: [
      "Technologie Quantum Matrix",
      "Neo Quantum HDR+",
      "Dolby Atmos®",
      "Motion Xcelerator 120Hz",
      "Alexa intégré",
    ],
    inStock: true,
    isFeatured: true,
    rating: 4.6,
    reviews: 95,
    language: ["English", "French"],
  },
  {
    id: 7,
    name_en: 'LG 77" OLED evo G3 4K Smart TV',
    name_fr: 'LG 77" OLED evo G3 4K intelligente TV',
    brand: "LG",
    category: "OLED",
    price: 1299900,
    oldPrice: 1399900,
    size_en: "77 inches",
    size_fr: "77 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749004342/LG_77_OLED_evo_G3_4K_Smart_TV-_gy09in.png",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749004342/LG_77_OLED_evo_G3_4K_Smart_TV-_gy09in.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749004372/LG_77_OLED_evo_G3_4K_Smart_TV_2_qt5bhc.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749004402/LG_77_OLED_evo_G3_4K_Smart_TV_5_vsts1f.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749004546/LG_77_OLED_evo_G3_4K_Smart_TV_4_k0mkxt.jpg",
    ],
    tags: ["LG", "OLED", "4K", "Smart TV", "77 inch"],
    description_en:
      "Elevate your home cinema with the LG OLED evo G3, featuring Brightness Booster Max and Dolby Vision.",
    description_fr:
      "Améliorez votre cinéma maison avec le LG OLED evo G3, doté de Brightness Booster Max et Dolby Vision.",
    detailedDescription_en:
      "The LG OLED evo G3 represents the pinnacle of OLED technology with enhanced brightness and premium design.",
    detailedDescription_fr:
      "Le LG OLED evo G3 représente le summum de la technologie OLED avec une luminosité améliorée et un design haut de gamme.",
    features_en: [
      "Brightness Booster Max",
      "Dolby Vision IQ",
      "α9 AI Processor Gen6",
      "webOS 23",
      "NVIDIA G-Sync Compatible",
    ],
    features_fr: [
      "Brightness Booster Max",
      "Dolby Vision IQ",
      "Processeur α9 AI Gen6",
      "webOS 23",
      "Compatible NVIDIA G-Sync",
    ],
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 120,
    language: ["English", "French"],
  },
  {
    id: 8,
    name_en: 'Sony 65" BRAVIA XR A80L OLED 4K Smart TV',
    name_fr: 'Sony 65" BRAVIA XR A80L OLED 4K intelligente TV',
    brand: "Sony",
    category: "OLED",
    price: 1099900,
    oldPrice: 1199900,
    size_en: "65 inches",
    size_fr: "65 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749006346/Sony_65_BRAVIA_XR_A80L_OLED_4K_Smart_TV_y44wta.png",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749006346/Sony_65_BRAVIA_XR_A80L_OLED_4K_Smart_TV_y44wta.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749006391/Sony_65_BRAVIA_XR_A80L_OLED_4K_Smart_TV_4_vablpd.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749006419/Sony_65_BRAVIA_XR_A80L_OLED_4K_Smart_TV_3_ocdpml.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749006445/Sony_65_BRAVIA_XR_A80L_OLED_4K_Smart_TV_2_xxuofn.png",
    ],
    tags: ["Sony", "BRAVIA", "OLED", "4K", "Smart TV", "65 inch"],
    description_en:
      "Immerse yourself in cinematic visuals with the Sony BRAVIA XR A80L, powered by the Cognitive Processor XR.",
    description_fr:
      "Plongez dans des visuels cinématographiques avec le Sony BRAVIA XR A80L, alimenté par le processeur cognitif XR.",
    detailedDescription_en:
      "The Sony BRAVIA XR A80L delivers intelligent picture processing with OLED technology for stunning realism.",
    detailedDescription_fr:
      "Le Sony BRAVIA XR A80L offre un traitement d'image intelligent avec la technologie OLED pour un réalisme saisissant.",
    features_en: [
      "Cognitive Processor XR",
      "XR OLED Contrast Pro",
      "Google TV",
      "Acoustic Surface Audio+",
      "Dolby Vision & Atmos",
    ],
    features_fr: [
      "Processeur cognitif XR",
      "XR OLED Contrast Pro",
      "Google TV",
      "Acoustic Surface Audio+",
      "Dolby Vision & Atmos",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.7,
    reviews: 85,
    language: ["English", "French"],
  },
  {
    id: 9,
    name_en: 'TCL 75" Q7 QLED 4K Smart TV',
    name_fr: 'TCL 75" Q7 QLED 4K intelligente TV',
    brand: "TCL",
    category: "QLED",
    price: 699900,
    oldPrice: 749900,
    size_en: "75 inches",
    size_fr: "75 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749008338/TCL_75_Q7_QLED_4K_Smart_TV_yxgmxa.jpg",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749008338/TCL_75_Q7_QLED_4K_Smart_TV_yxgmxa.jpg",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749008357/TCL_75_Q7_QLED_4K_Smart_TV_2_f75gic.webp",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749008376/TCL_75_Q7_QLED_4K_Smart_TV_3_uanvig.webp",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749008394/TCL_75_Q7_QLED_4K_Smart_TV_4_opukjy.png",
    ],
    tags: ["TCL", "QLED", "4K", "Smart TV", "75 inch"],
    description_en: "Enjoy vibrant colors and smooth motion with the TCL Q7 QLED TV, featuring Game Accelerator 240.",
    description_fr:
      "Profitez de couleurs éclatantes et d'un mouvement fluide avec le téléviseur TCL Q7 QLED, doté de Game Accelerator 240.",
    detailedDescription_en:
      "The TCL Q7 QLED combines large screen entertainment with gaming-focused features for versatile performance.",
    detailedDescription_fr:
      "Le TCL Q7 QLED combine le divertissement grand écran avec des fonctionnalités axées sur le jeu pour des performances polyvalentes.",
    features_en: [
      "Quantum Dot Technology",
      "Game Accelerator 240",
      "HDR PRO+ (Dolby Vision, HDR10+)",
      "Google TV",
      "Dolby Atmos",
    ],
    features_fr: [
      "Technologie Quantum Dot",
      "Game Accelerator 240",
      "HDR PRO+ (Dolby Vision, HDR10+)",
      "Google TV",
      "Dolby Atmos",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.5,
    reviews: 70,
    language: ["English", "French"],
  },
  {
    id: 10,
    name_en: 'Hisense 65" U8K Mini-LED ULED 4K Smart TV',
    name_fr: 'Hisense 65" U8K Mini-LED ULED 4K intelligente TV',
    brand: "Hisense",
    category: "ULED",
    price: 599900,
    oldPrice: 649900,
    size_en: "65 inches",
    size_fr: "65 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749090753/Hisense_65_U8K_Mini-LED_ULED_4K_Smart_TV_aqlh9u.png",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749090753/Hisense_65_U8K_Mini-LED_ULED_4K_Smart_TV_aqlh9u.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749090782/Hisense_65_U8K_Mini-LED_ULED_4K_Smart_TV_2_h7ceix.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749090815/Hisense_65_U8K_Mini-LED_ULED_4K_Smart_TV_3_nfc3cv.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749090841/Hisense_65_U8K_Mini-LED_ULED_4K_Smart_TV_4_tp9qsc.png",
    ],
    tags: ["Hisense", "ULED", "4K", "Smart TV", "65 inch"],
    description_en:
      "Experience ultra-bright visuals and smooth motion with the Hisense U8K, featuring Mini-LED technology and Dolby Atmos audio.",
    description_fr:
      "Découvrez des visuels ultra-lumineux et un mouvement fluide avec le Hisense U8K, doté de la technologie Mini-LED et de l'audio Dolby Atmos.",
    detailedDescription_en:
      "The Hisense U8K Mini-LED delivers exceptional brightness control and contrast with advanced local dimming technology.",
    detailedDescription_fr:
      "Le Hisense U8K Mini-LED offre un contrôle de luminosité et un contraste exceptionnels avec une technologie de gradation locale avancée.",
    features_en: [
      "Mini-LED Pro Backlight",
      "Quantum Dot Color",
      "144Hz Native Refresh Rate",
      "Dolby Vision & Atmos",
      "Google TV with Voice Remote",
    ],
    features_fr: [
      "Rétroéclairage Mini-LED Pro",
      "Couleur Quantum Dot",
      "Taux de rafraîchissement natif de 144 Hz",
      "Dolby Vision & Atmos",
      "Google TV avec télécommande vocale",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.6,
    reviews: 90,
    language: ["English", "French"],
  },
  {
    id: 11,
    name_en: 'Samsung 48J6300 Curved LED TV 48"',
    name_fr: 'Samsung 48J6300 TV LED incurvée 48"',
    brand: "Samsung",
    category: "Curved 4K",
    price: 140000,
    oldPrice: 150000,
    size_en: "48 inches",
    size_fr: "48 pouces",
    resolution: "Full HD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749092929/samsung-led-48J6300-1_dpnsmv.jpg",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749092929/samsung-led-48J6300-1_dpnsmv.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749092958/samsung-led-48J6300-2_d3dojh.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749092979/samsung-led-48J6300-3_kgw3zz.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749092996/samsung-led-48J6300-4_hsfysx.jpg",
    ],
    tags: ["Samsung", "Curved", "4K", "Smart TV", "48 inch"],
    description_en:
      "Enjoy immersive viewing with the Samsung 48J6300, a curved Full HD TV with built-in WiFi, streaming apps, and sleek wall-mountable design.",
    description_fr:
      "Profitez d'une expérience immersive avec le Samsung 48J6300, un téléviseur Full HD incurvé avec WiFi intégré, applications de streaming et design élégant montable au mur.",
    detailedDescription_en:
      "The Samsung 48J6300 features a curved display that provides an immersive viewing experience with enhanced depth perception.",
    detailedDescription_fr:
      "Le Samsung 48J6300 dispose d'un écran incurvé qui offre une expérience de visionnage immersive avec une perception de profondeur améliorée.",
    features_en: [
      "Prime Video",
      "Built-in WiFi",
      "YouTube and Netflix",
      "Low-power LED display",
      "Wall mount support",
      "HDMI",
      "3 USB ports",
    ],
    features_fr: [
      "Prime Video",
      "WiFi intégré",
      "YouTube et Netflix",
      "Écran LED à faible consommation",
      "Support mural",
      "HDMI",
      "3 ports USB",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.3,
    reviews: 27,
    language: ["English", "French"],
  },
  {
    id: 12,
    name_en: "PHILIPS 43-inch Ultra HD 4K LED TV",
    name_fr: "PHILIPS 43 pouces Ultra HD 4K LED TV",
    brand: "PHILIPS",
    category: "Ultra HDR",
    price: 110000,
    oldPrice: 130000,
    size_en: "43 inches",
    size_fr: "43 pouces",
    resolution: "Full HD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093340/phillips-hdr-4k-1_sm523i.jpg",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093340/phillips-hdr-4k-1_sm523i.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093360/phillips-hdr-4k-2_yqyjjj.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093374/phillips-hdr-4k-3_c6fq9g.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093397/phillips-hdr-4k-4_g5ulyn.jpg",
    ],
    tags: ["PHILIPS", "Ultra HDR", "4K", "Smart TV", "43 inch"],
    description_en:
      "Enjoy rich, ultra-clear visuals with the PHILIPS 43-inch Ultra HD 4K LED TV. This slim, modern Smart TV features an integrated decoder, built-in WiFi, and supports popular streaming platforms.",
    description_fr:
      "Profitez de visuels riches et ultra-clairs avec le téléviseur LED PHILIPS 43 pouces Ultra HD 4K. Ce téléviseur intelligent mince et moderne dispose d'un décodeur intégré, du WiFi intégré et prend en charge les plateformes de streaming populaires.",
    detailedDescription_en:
      "The PHILIPS Ultra HD 4K LED TV combines modern design with advanced technology for exceptional home entertainment.",
    detailedDescription_fr:
      "Le téléviseur LED PHILIPS Ultra HD 4K combine un design moderne avec une technologie avancée pour un divertissement domestique exceptionnel.",
    features_en: [
      "Prime Video",
      "Built-in WiFi",
      "YouTube and Netflix",
      "Low-power LED display",
      "Wall mount support",
      "HDMI",
      "3 USB ports",
      "Built-in Decoder",
      "CANAL+ Channels Access",
    ],
    features_fr: [
      "Prime Video",
      "WiFi intégré",
      "YouTube et Netflix",
      "Écran LED à faible consommation",
      "Support mural",
      "HDMI",
      "3 ports USB",
      "Décodeur intégré",
      "Accès aux chaînes CANAL+",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.4,
    reviews: 32,
    language: ["English", "French"],
  },
  {
    id: 13,
    name_en: 'Samsung 40J6300 Slim Bezel LED TV 40"',
    name_fr: 'Samsung 40J6300 TV LED bordure mince 40"',
    brand: "Samsung",
    category: "Full HD",
    price: 90000,
    oldPrice: 110000,
    size_en: "40 inches",
    size_fr: "40 pouces",
    resolution: "4K",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093872/samsung-led-40J6300-1_qwx8dk.jpg",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093872/samsung-led-40J6300-1_qwx8dk.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093887/samsung-led-40J6300-2_lldj1q.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093929/samsung-led-40J6300-3_z6iy0w.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749093971/samsung-led-40J6300-4_eo7zbw.jpg",
    ],
    tags: ["Samsung", "Full HD", "4K", "Smart TV", "40 inch"],
    description_en:
      "Experience clarity and convenience with the Samsung 40J6300 Slim Bezel TV. With built-in WiFi, support for YouTube and Netflix, and a durable build, this 40-inch Smart TV is both stylish and practical.",
    description_fr:
      "Découvrez la clarté et la commodité avec le téléviseur Samsung 40J6300 à bordure mince. Avec WiFi intégré, prise en charge de YouTube et Netflix, et une construction durable, ce téléviseur intelligent de 40 pouces est à la fois élégant et pratique.",
    detailedDescription_en:
      "The Samsung 40J6300 features a slim bezel design that maximizes screen space while maintaining elegant aesthetics.",
    detailedDescription_fr:
      "Le Samsung 40J6300 dispose d'un design à bordure mince qui maximise l'espace d'écran tout en conservant une esthétique élégante.",
    features_en: [
      "Built-in WiFi",
      "YouTube and Netflix",
      "Low-power LED display",
      "Wall mount and stand support",
      "2 HDMI ports",
      "USB ports",
    ],
    features_fr: [
      "WiFi intégré",
      "YouTube et Netflix",
      "Écran LED à faible consommation",
      "Support mural et support",
      "2 ports HDMI",
      "Ports USB",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.2,
    reviews: 24,
    language: ["English", "French"],
  },
  {
    id: 14,
    name_en: "Samsung 50-inch LED UA50DU7000KXMR Slim Bezel TV",
    name_fr: "Samsung 50 pouces LED UA50DU7000KXMR TV bordure mince",
    brand: "Samsung",
    category: "Full HD",
    price: 140000,
    oldPrice: 165000,
    size_en: "50 inches",
    size_fr: "50 pouces",
    resolution: "4K",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749206632/samsung-led-UA50DU7000KXMR-1_rpiadr.jpg",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749206632/samsung-led-UA50DU7000KXMR-1_rpiadr.jpg",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749206662/samsung-led-UA50DU7000KXMR-2_u2pq52.jpg",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749206691/samsung-led-UA50DU7000KXMR-3_fkaf7d.jpg",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749206713/samsung-led-UA50DU7000KXMR-4_riak0b.jpg",
    ],
    tags: ["Samsung", "Full HD", "4K", "Smart TV", "50 inch"],
    description_en:
      "Elevate your viewing with the Samsung 50-inch UA50DU7000KXMR LED TV. With Full HD and 4K resolution, built-in WiFi, and support for popular apps like YouTube, Netflix, and Prime Video, this slim bezel TV combines powerful performance with modern aesthetics.",
    description_fr:
      "Améliorez votre expérience de visionnage avec le téléviseur LED Samsung 50 pouces UA50DU7000KXMR. Avec résolution Full HD et 4K, WiFi intégré et prise en charge d'applications populaires comme YouTube, Netflix et Prime Video, ce téléviseur à bordure mince combine performance puissante et esthétique moderne.",
    detailedDescription_en:
      "The Samsung UA50DU7000KXMR offers excellent value with its combination of 4K resolution, smart features, and reliable build quality.",
    detailedDescription_fr:
      "Le Samsung UA50DU7000KXMR offre un excellent rapport qualité-prix avec sa combinaison de résolution 4K, de fonctionnalités intelligentes et de qualité de construction fiable.",
    features_en: [
      "Built-in WiFi",
      "YouTube, Netflix, and Prime Video support",
      "Low-power LED display",
      "Wall mount and stand support",
      "2 HDMI ports",
      "USB ports",
    ],
    features_fr: [
      "WiFi intégré",
      "Prise en charge de YouTube, Netflix et Prime Video",
      "Écran LED à faible consommation",
      "Support mural et support",
      "2 ports HDMI",
      "Ports USB",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.5,
    reviews: 38,
    language: ["English", "French"],
  },
  {
    id: 15,
    name_en: 'Roku 55" 4K QLED Pro Series TV',
    name_fr: 'Roku 55" 4K QLED Pro Series TV',
    brand: "Roku",
    category: "QLED",
    price: 449900,
    oldPrice: 499900,
    size_en: "55 inches",
    size_fr: "55 pouces",
    resolution: "4K UHD",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749277699/Roku_55_4K_QLED_Pro_Series_TV_orajye.png",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749277699/Roku_55_4K_QLED_Pro_Series_TV_orajye.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749277740/Roku_55_4K_QLED_Pro_Series_TV_2_k6sve3.webp",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749277944/Roku_55_4K_QLED_Pro_Series_TV_3_benlnw.png",
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749278031/Roku_55_4K_QLED_Pro_Series_TV_4_kjrcmn.webp",
    ],
    tags: ["Roku", "QLED", "4K", "Smart TV", "55 inch"],
    description_en:
      'Experience premium streaming with the Roku 55" 4K QLED Pro Series TV, featuring Quantum Dot technology and the intuitive Roku OS.',
    description_fr:
      "Découvrez le streaming premium avec le téléviseur Roku 55\" 4K QLED Pro Series, doté de la technologie Quantum Dot et du système d'exploitation Roku intuitif.",
    detailedDescription_en:
      "The Roku 4K QLED Pro Series delivers exceptional picture quality with Quantum Dot technology and seamless streaming experience.",
    detailedDescription_fr:
      "Le Roku 4K QLED Pro Series offre une qualité d'image exceptionnelle avec la technologie Quantum Dot et une expérience de streaming fluide.",
    features_en: ["Quantum Dot Technology", "Roku OS", "Voice Remote Pro", "Dolby Vision HDR", "Game Mode"],
    features_fr: ["Technologie Quantum Dot", "Roku OS", "Télécommande vocale Pro", "Dolby Vision HDR", "Mode Jeu"],
    inStock: true,
    isFeatured: false,
    rating: 4.4,
    reviews: 65,
    language: ["English", "French"],
  },
  {
    id: 16,
    name_en: "LG NanoCell 50-inch 50NANO79VND Slim Bezel TV",
    name_fr: "LG NanoCell 50 pouces 50NANO79VND TV bordure mince",
    brand: "LG",
    category: "Full HD",
    price: 150000,
    oldPrice: 160000,
    size_en: "50 inches",
    size_fr: "50 pouces",
    resolution: "4K",
    image: "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749344104/LG-NANOCELL-1_p4iywy.jpg",
    additionalImages: [
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749344104/LG-NANOCELL-1_p4iywy.jpg", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749346757/LG-NANOCELL-2_1_yqwbgm.webp", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749346787/LG-NANOCELL-3_zflupf.webp", 
      "https://res.cloudinary.com/dip0otvct/image/upload/f_auto,q_auto/v1749344722/LG-NANOCELL-4_kqx3fo.jpg"
    ],
    tags: ["LG", "NanoCell", "Full HD", "4K", "Smart TV", "50 inch"],
    description_en:
      "Discover stunning picture quality with the LG NanoCell 50NANO79VND 50-inch TV. This smart TV features Full HD and 4K resolution, a slim bezel design, and built-in WiFi. Enjoy your favorite apps like YouTube, Netflix, and Prime Video.",
    description_fr:
      "Découvrez une qualité d'image époustouflante avec le téléviseur LG NanoCell 50NANO79VND 50 pouces. Ce téléviseur intelligent dispose d'une résolution Full HD et 4K, d'un design à bordure mince et du WiFi intégré. Profitez de vos applications préférées comme YouTube, Netflix et Prime Video.",
    detailedDescription_en:
      "The LG NanoCell technology delivers pure colors and enhanced clarity for an immersive viewing experience.",
    detailedDescription_fr:
      "La technologie LG NanoCell offre des couleurs pures et une clarté améliorée pour une expérience de visionnage immersive.",
    features_en: [
      "Built-in WiFi",
      "YouTube, Netflix, and Prime Video support",
      "Low-power LED display",
      "Wall mount and stand support",
      "2 HDMI ports",
      "USB ports",
    ],
    features_fr: [
      "WiFi intégré",
      "Prise en charge de YouTube, Netflix et Prime Video",
      "Écran LED à faible consommation",
      "Support mural et support",
      "2 ports HDMI",
      "Ports USB",
    ],
    inStock: true,
    isFeatured: false,
    rating: 4.6,
    reviews: 41,
    language: ["English", "French"],
  },
]

// Add these optimizations to your data.js:

// 1. Add image size parameters to Cloudinary URLs
const optimizeImageUrl = (url) => {
  return url.replace('/upload/', '/upload/w_auto,c_scale,q_auto,f_auto/');
};

// 2. Add a function to get optimized images
const getOptimizedImages = (product) => {
  return {
    ...product,
    image: optimizeImageUrl(product.image),
    additionalImages: product.additionalImages.map(img => optimizeImageUrl(img))
  };
};

// 3. Create optimized data
const optimizedSmartTVs = smartTVs.map(getOptimizedImages);

// Export both the original and optimized data
export { optimizedSmartTVs };
export default smartTVs;
