const smartTVs = [
    {
      id: 1,
      name: "Samsung QN90D Neo QLED 4K Smart TV 55\"",
      brand: "Samsung",
      category: "Neo QLED",
      price: 649900, // in CFA
      oldPrice: 699900,
      size: "55 inches",
      resolution: "4K UHD",
      image: "https://image-us.samsung.com/SamsungUS/home/television-home-theater/tvs/103124/QN43QN90DAFXZA_S_COM_Version_2_V01_1.jpg?$product-details-jpg$",
      tags: ["Samsung", "Neo QLED", "4K", "Smart TV", "55 inch"],
      description: "Experience brilliant 4K picture with Quantum Dot technology and AI-powered upscaling.",
      features: [
        "Quantum Dot Technology",
        "AI-Powered Upscaling",
        "HDR10+ Support",
        "Multiple HDMI Ports",
        "Voice Control"
      ],
      inStock: true,
      isFeatured: true,
      rating: 4.7,
      reviews: 120,
      language: ["English", "French"],
      whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20Samsung%20QN90D%20Neo%20QLED%204K%20Smart%20TV%2055%22"
    },
    {
      id: 2,
      name: "LG OLED evo C3 65\" 4K Smart TV",
      brand: "LG",
      category: "OLED",
      price: 799900,
      oldPrice: 849900,
      size: "65 inches",
      resolution: "4K UHD",
      image: "https://i5.walmartimages.com/seo/LG-65-Class-4K-UHD-OLED-Web-OS-Smart-TV-with-Dolby-Vision-C3-Series-OLED65C3PUA_4507d0a3-83cb-4420-9c59-ef2c191d7fe7.3c9fdb1665a5e2074e0c8c38fc251fff.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF",
      tags: ["LG", "OLED", "4K", "Smart TV", "65 inch"],
      description: "Enjoy perfect black levels and infinite contrast with self-lighting OLED pixels.",
      features: [
        "Self-Lighting OLED",
        "Dolby Vision IQ",
        "NVIDIA G-Sync Support",
        "AI Picture Pro",
        "webOS Platform"
      ],
      inStock: true,
      isFeatured: true,
      rating: 4.8,
      reviews: 150,
      language: ["English", "French"],
      whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20LG%20OLED%20evo%20C3%2065%22%204K%20Smart%20TV"
    },
    {
      id: 3,
      name: "Sony Bravia 3 50\" 4K HDR Google TV",
      brand: "Sony",
      category: "LED",
      price: 499900,
      oldPrice: 549900,
      size: "50 inches",
      resolution: "4K UHD",
      image: "https://d1ncau8tqf99kp.cloudfront.net/converted/118893_original_local_1200x1050_v3_converted.webp",
      tags: ["Sony", "Bravia", "4K", "Smart TV", "50 inch"],
      description: "Experience vibrant visuals and immersive sound with Google TV integration.",
      features: [
        "4K HDR Processor",
        "Google TV Interface",
        "Dolby Vision Support",
        "Motionflow XR",
        "Built-in Chromecast"
      ],
      inStock: true,
      isFeatured: false,
      rating: 4.5,
      reviews: 80,
      language: ["English", "French"],
      whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20Sony%20Bravia%203%2050%22%204K%20HDR%20Google%20TV"
    },
    {
      id: 4,
      name: "TCL 43\" Q Class 4K UHD HDR QLED Smart TV",
      brand: "TCL",
      category: "QLED",
      price: 349900,
      oldPrice: 399900,
      size: "43 inches",
      resolution: "4K UHD",
      image: "https://www.tcl.com/usca/content/dam/tcl/product/home-theater/q-class/43q51bg/43Q51BG-UI_Front.png",
      tags: ["TCL", "QLED", "4K", "Smart TV", "43 inch"],
      description: "Enjoy vibrant colors and deep contrasts with Quantum Dot technology.",
      features: [
        "Quantum Dot Technology",
        "Dolby Vision HDR",
        "Google TV Interface",
        "Auto Game Mode",
        "Built-in Chromecast"
      ],
      inStock: true,
      isFeatured: false,
      rating: 4.3,
      reviews: 60,
      language: ["English", "French"],
      whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20TCL%2043%22%20Q%20Class%204K%20UHD%20HDR%20QLED%20Smart%20TV"
    },
    {
      id: 5,
      name: "Hisense 58\" Quantum ULED 4K Fire TV",
      brand: "Hisense",
      category: "ULED",
      price: 599900,
      oldPrice: 649900,
      size: "58 inches",
      resolution: "4K UHD",
      image: "https://m.media-amazon.com/images/I/61W9PZAWKTL._AC_SX569_.jpg",
      tags: ["Hisense", "ULED", "4K", "Smart TV", "58 inch"],
      description: "Experience cinematic quality with Quantum Dot and Dolby Vision support.",
      features: [
        "Quantum Dot Technology",
        "Dolby Vision HDR",
        "Fire TV OS",
        "Motion Rate 240",
        "Alexa Built-in"
      ],
      inStock: true,
      isFeatured: false,
      rating: 4.4,
      reviews: 70,
      language: ["English", "French"],
      whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20Hisense%2058%22%20Quantum%20ULED%204K%20Fire%20TV"
    },
    {
        id: 6,
        name: "Samsung 65\" QN85D Neo QLED 4K Smart TV",
        brand: "Samsung",
        category: "Neo QLED",
        price: 799900,
        oldPrice: 899900,
        size: "65 inches",
        resolution: "4K UHD",
        image: "https://m.media-amazon.com/images/I/61Rl2U7ZBSL._AC_SX425_.jpg",
        tags: ["Samsung", "Neo QLED", "4K", "Smart TV", "65 inch"],
        description: "Experience stunning visuals with Quantum Matrix Technology and Neo Quantum HDR+ for immersive viewing.",
        features: [
          "Quantum Matrix Technology",
          "Neo Quantum HDR+",
          "Dolby Atmos®",
          "Motion Xcelerator 120Hz",
          "Built-in Alexa"
        ],
        inStock: true,
        isFeatured: true,
        rating: 4.6,
        reviews: 95,
        language: ["English", "French"],
        whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20Samsung%2065%22%20QN85D%20Neo%20QLED%204K%20Smart%20TV"
      },
      {
        id: 7,
        name: "LG 77\" OLED evo G3 4K Smart TV",
        brand: "LG",
        category: "OLED",
        price: 1299900,
        oldPrice: 1399900,
        size: "77 inches",
        resolution: "4K UHD",
        image: "https://m.media-amazon.com/images/I/81Juoqh6lXL._AC_SX425_.jpg",
        tags: ["LG", "OLED", "4K", "Smart TV", "77 inch"],
        description: "Elevate your home cinema with the LG OLED evo G3, featuring Brightness Booster Max and Dolby Vision.",
        features: [
          "Brightness Booster Max",
          "Dolby Vision IQ",
          "α9 AI Processor Gen6",
          "webOS 23",
          "NVIDIA G-Sync Compatible"
        ],
        inStock: true,
        isFeatured: true,
        rating: 4.9,
        reviews: 120,
        language: ["English", "French"],
        whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20LG%2077%22%20OLED%20evo%20G3%204K%20Smart%20TV"
      },
      {
        id: 8,
        name: "Sony 65\" BRAVIA XR A80L OLED 4K Smart TV",
        brand: "Sony",
        category: "OLED",
        price: 1099900,
        oldPrice: 1199900,
        size: "65 inches",
        resolution: "4K UHD",
        image: "https://m.media-amazon.com/images/I/71jD+F4efVL._AC_SX425_.jpg",
        tags: ["Sony", "BRAVIA", "OLED", "4K", "Smart TV", "65 inch"],
        description: "Immerse yourself in cinematic visuals with the Sony BRAVIA XR A80L, powered by the Cognitive Processor XR.",
        features: [
          "Cognitive Processor XR",
          "XR OLED Contrast Pro",
          "Google TV",
          "Acoustic Surface Audio+",
          "Dolby Vision & Atmos"
        ],
        inStock: true,
        isFeatured: false,
        rating: 4.7,
        reviews: 85,
        language: ["English", "French"],
        whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20Sony%2065%22%20BRAVIA%20XR%20A80L%20OLED%204K%20Smart%20TV"
      },
      {
        id: 9,
        name: "TCL 75\" Q7 QLED 4K Smart TV",
        brand: "TCL",
        category: "QLED",
        price: 699900,
        oldPrice: 749900,
        size: "75 inches",
        resolution: "4K UHD",
        image: "https://m.media-amazon.com/images/I/81ZWqj7nrUL._AC_SX425_.jpg",
        tags: ["TCL", "QLED", "4K", "Smart TV", "75 inch"],
        description: "Enjoy vibrant colors and smooth motion with the TCL Q7 QLED TV, featuring Game Accelerator 240.",
        features: [
          "Quantum Dot Technology",
          "Game Accelerator 240",
          "HDR PRO+ (Dolby Vision, HDR10+)",
          "Google TV",
          "Dolby Atmos"
        ],
        inStock: true,
        isFeatured: false,
        rating: 4.5,
        reviews: 70,
        language: ["English", "French"],
        whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20TCL%2075%22%20Q7%20QLED%204K%20Smart%20TV"
      },
      {
        id: 10,
        name: "Hisense 65\" U8K Mini-LED ULED 4K Smart TV",
        brand: "Hisense",
        category: "ULED",
        price: 599900,
        oldPrice: 649900,
        size: "65 inches",
        resolution: "4K UHD",
        image: "https://m.media-amazon.com/images/I/71cJVrOAVNL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
        tags: ["Hisense", "ULED", "4K", "Smart TV", "65 inch"],
        description: "Experience ultra-bright visuals and smooth motion with the Hisense U8K, featuring Mini-LED technology and Dolby Atmos audio.",
        features: [
          "Mini-LED Pro Backlight",
          "Quantum Dot Color",
          "144Hz Native Refresh Rate",
          "Dolby Vision & Atmos",
          "Google TV with Voice Remote"
        ],
        inStock: true,
        isFeatured: false,
        rating: 4.6,
        reviews: 90,
        language: ["English", "French"],
        whatsappLink: "https://wa.me/2250700000000?text=I'm%20interested%20in%20the%20Hisense%2065%22%20U8K%20Mini-LED%20ULED%204K%20Smart%20TV"
    }
  ];
  
  export default smartTVs;
  